# holy shit its a website!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <p style="color:green; font-family:helvetica">o shit waddup
email: talamvicknair@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  holy shit its a website??????????? how?????
baseurl: "" # the subpath of your site, e.g. /blog
url: "ultra-dweeb-trash.tumblr.com" # the base hostname & protocol for your site
twitter_username: a
github_username:  yy

# Build settings
markdown: kramdown
