# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: <p>
email: talamvicknair@gmail.com
description: <p style="color:purple;font-family:helvetica"> # this means to ignore newlines until "baseurl:"
  testing website for yea
baseurl: "ultra-dweeb-trash.tumblr.com" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: ---
github_username:  jackferrara

# Build settings
markdown: kramdown
